/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.eng.cepmiddleware.api.v1.engine;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "engines", description = "the engines API")
public interface EngineApi {

    @ApiOperation(value = "Returns info about the engine")
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 404, message = "Requested CEP engine does not exist")
    })
    @RequestMapping(value = "/engines/{engineId}", method = RequestMethod.GET)
    ResponseEntity<?> getEngine(@ApiParam(value = "",required=true) @PathVariable("engineId") String engineId);

    @ApiOperation(value = "Returns all available CEP engines")
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation")
    })
    @RequestMapping(value = "/engines", method = RequestMethod.GET)
    ResponseEntity<?> getEngines();

}
