version: '3'

services:

  mongo:
    image: mongo:3.2
    container_name: mongo
    ports:
      - "27017:27017"
    command: --nojournal
    networks:
      fiwareNetwork:
        aliases:
          - mongo
    volumes:
    - ./data:/data

  orion:
    image: fiware/orion
    container_name: orion
    ports:
      - "1026:1026"
    command:
      -dbhost mongo
      -corsOrigin __ALL
      -logLevel DEBUG
    networks:
      fiwareNetwork:
        aliases:
          - orion
    depends_on:
      - mongo

  perseo-core:
    image: telefonicaiot/perseo-core
    container_name: perseo-core
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - orion
    command: -perseo_fe_url perseo-fe:9090
    networks:
      fiwareNetwork:
        aliases:
          - perseo-core

  perseo-fe:
    image: telefonicaiot/perseo-fe
    container_name: perseo-fe
    ports:
      - "9090:9090"
    depends_on:
      - mongo
      - orion
      - perseo-core
    environment:
      - PERSEO_MONGO_ENDPOINT=mongo
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_LOG_LEVEL=debug
      - PERSEO_ORION_URL=http://orion:1026/v1/updateContext
    networks:
      fiwareNetwork:
        aliases:
          - perseo-fe

  PostgreSQL:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=postgres
    networks:
      fiwareNetwork:
        aliases:
          - PostgreSQL

  CEP-middleware:
    build:
      context: https://github.com/is3labengrd/cep-middleware.git#develop
    image: drobniac/cep-middleware
    container_name: cep-middleware
    ports:
      - "8091:8090"
    depends_on:
      - PostgreSQL
      - perseo-fe
      - perseo-core
    command:
      --server.port=8090
      --spring.datasource.url="jdbc:postgresql://PostgreSQL:5432/postgres"
      --spring.jpa.hibernate.ddl-auto="create"
      --spring.datasource.username="root"
      --spring.datasource.password="root"
    networks:
      fiwareNetwork:
        aliases:
          - CEP-middleware

  mysql:
    image: mysql/mysql-server:5.7.21
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      fiwareNetwork:
        aliases:
          - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=idm
      - MYSQL_ROOT_HOST=%

  fiware-idm:
    image: waste4think/fiware-idm
    container_name: idm
    ports:
      - "3000:8000"
      - "443:5000"
    networks:
      fiwareNetwork:
        aliases:
          - fiware-idm
    environment:
      - DATABASE_HOST=mysql

  fiware-pep:
    image: waste4think/pep_proxy:release-6.2
    container_name: pep
    ports:
      - 9191:80
    volumes:
      - ./config.js:/opt/fiware-pep-proxy/config.js
    networks:
      fiwareNetwork:
        aliases:
          - fiware-pep

  authzforce:
    image: fiware/authzforce-ce-server:release-8.0.1
    container_name: authzforce
    ports:
      - 9292:8080
    networks:
      fiwareNetwork:
        aliases:
          - authzforce

networks:

  fiwareNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28
