/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.eng.cepmiddleware.api.v1;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "default", description = "the default API")
public interface DefaultApi {

    @ApiOperation(value = "Provides possible operations within the API")
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation")
    })
    @RequestMapping(value = "/", method = RequestMethod.GET)
    ResponseEntity<?> rootGet();

}
